### ISSUE TITLE
Headless execution fails after execution.

### ISSUE THREAD

**Issue by aylakhan** [SCIInstitute/SCIRun#572]
Tested on OS X 10.7 on headless branch. Need to test on more platforms (i.e. Linux, OS X 10.9, etc).

(gdb) run
Starting program: /Volumes/scratch/SCIRunGUIPrototype_headless/bin.debug/SCIRun -e ../src/ExampleNets/regression/writeBadFile_new.srn5
Reading symbols for shared libraries ++++++++++++++++++++++++++++++++++++++++++++++++++++++.................................................................................................................................. done
Caught ConfigureFailure exception: unterminated conversion specifier in '%d{%Y-%m-%d %H:%M:%S.%l} %c [%p] %m%n' at index -1
Restoring original pattern: ()
Caught ConfigureFailure exception: unterminated conversion specifier in '%d{%Y-%m-%d %H:%M:%S.%l} %c [%p] %m%n' at index -1
Restoring original pattern: ()
Caught ConfigureFailure exception: unterminated conversion specifier in '%d{%Y-%m-%d %H:%M:%S.%l} %c [%p] %m%n' at index -1
Restoring original pattern: ()
Caught ConfigureFailure exception: unterminated conversion specifier in '%d{%Y-%m-%d %H:%M:%S.%l} %c [%p] %m%n' at index -1
Restoring original pattern: ()
Caught ConfigureFailure exception: unterminated conversion specifier in '%d{%Y-%m-%d %H:%M:%S.%l} %c [%p] %m%n' at index -1
Restoring original pattern: ()
Caught ConfigureFailure exception: unterminated conversion specifier in '%d{%Y-%m-%d %H:%M:%S.%l} %c [%p] %m%n' at index -1
Restoring original pattern: ()
Attempting load of ../src/ExampleNets/regression/writeBadFile_new.srn5
File load done.
ExecuteCurrentNetworkCommandConsole::execute()
execution done

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: 13 at address: 0x0000000000000000
[Switching to process 76298 thread 0x4b03]
boost::detail::sp_counted_base::use_count (this=0x1000000000000000) at sp_counted_base_gcc_x86.hpp:166
166	        return static_cast<int const volatile &>( use_count_ );
(gdb) bt
#0  boost::detail::sp_counted_base::use_count (this=0x1000000000000000) at sp_counted_base_gcc_x86.hpp:166
#1  0x000000010013b83d in boost::detail::shared_count::use_count (this=0x1093164a8) at shared_count.hpp:423
#2  0x000000010013b7f5 in boost::detail::shared_count::unique (this=0x1093164a8) at shared_count.hpp:428
#3  0x0000000100ec84d5 in boost::shared_ptr<boost::signals2::detail::signal_impl<void ()(), boost::signals2::optional_last_value<void>, int, std::__1::less<int>, boost::function<void ()()>, boost::function<void ()(boost::signals2::connection const&)>, boost::signals2::mutex>::invocation_state>::unique (this=0x1093164a0) at shared_ptr.hpp:676
#4  0x0000000100ec80f5 in boost::signals2::detail::signal_impl<void ()(), boost::signals2::optional_last_value<void>, int, std::__1::less<int>, boost::function<void ()()>, boost::function<void ()(boost::signals2::connection const&)>, boost::signals2::mutex>::operator() (this=0x1093164a0) at signal_template.hpp:231
#5  0x0000000100eb6484 in boost::signals2::signal<void ()(), boost::signals2::optional_last_value<void>, int, std::__1::less<int>, boost::function<void ()()>, boost::function<void ()(boost::signals2::connection const&)>, boost::signals2::mutex>::operator() (this=0x100f69758) at signal_template.hpp:699
#6  0x0000000100f272f7 in SCIRun::Dataflow::Engine::ScopedExecutionBoundsSignaller::ScopedExecutionBoundsSignaller (this=0x10a080e30, bounds=@0x100f69750, errorCodeRetriever=<value temporarily unavailable, due to optimizations>) at /Volumes/scratch/SCIRunGUIPrototype_headless/src/Dataflow/Engine/Scheduler/SchedulerInterfaces.cc:35
#7  0x0000000100f272ad in SCIRun::Dataflow::Engine::ScopedExecutionBoundsSignaller::ScopedExecutionBoundsSignaller (this=0x10a080e30, bounds=@0x100f69750, errorCodeRetriever=@0x100f69758) at /Volumes/scratch/SCIRunGUIPrototype_headless/src/Dataflow/Engine/Scheduler/SchedulerInterfaces.cc:36
#8  0x0000000100eebdca in SCIRun::Dataflow::Engine::DynamicExecutor::ModuleProducer::operator() (this=0x10938e4a0) at WorkUnitProducer.h:102
#9  0x0000000100eebd5c in boost::detail::thread_data<boost::reference_wrapper<SCIRun::Dataflow::Engine::DynamicExecutor::ModuleProducer> const>::run (this=0x109600230) at thread.hpp:154
#10 0x0000000108fd3c55 in thread_proxy (param=0x109600230) at libs/thread/src/pthread/thread.cpp:164
#11 0x00007fff845348bf in _pthread_start ()
#12 0x00007fff84537b75 in thread_start ()
(gdb) f 9
#9  0x0000000100eebd5c in boost::detail::thread_data<boost::reference_wrapper<SCIRun::Dataflow::Engine::DynamicExecutor::ModuleProducer> const>::run (this=0x109600230) at thread.hpp:154
154	                f();
(gdb) list
149	            thread_data(const boost::reference_wrapper<F> f_):
150	                f(f_)
151	            {}
152	            void run()
153	            {
154	                f();
155	            }
156	        };
157	#endif
158	    }
(gdb) f 8
#8  0x0000000100eebdca in SCIRun::Dataflow::Engine::DynamicExecutor::ModuleProducer::operator() (this=0x10938e4a0) at WorkUnitProducer.h:102
102	            ScopedExecutionBoundsSignaller signaller(bounds_, [=]() { return lookup_->errorCode(); });
(gdb) list
97	            }
98	          }
99	
100	          void operator()() const
101	          {
102	            ScopedExecutionBoundsSignaller signaller(bounds_, [=]() { return lookup_->errorCode(); });
103	
104	            if (shouldLog_)
105	              log_ << Core::Logging::DEBUG_LOG << "Producer started" << std::endl;
106	
(gdb)

**Comment by aylakhan** [comment]
This particular executor bug with headless execution appears to be fixed.
